modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Mrbysco/JustARaftMod"
license="MIT"

[[mods]]
modId="justaraftmod"
version="${file.jarVersion}"
displayName="Just A Raft Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/just-a-raft-mod"
authors="Mrbysco, ShyNieke"
description='''
Adding rafts since 2017
'''
[[dependencies.justaraftmod]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"